website/views.py
from flask import Blueprint, render_template, flash, redirect, request, jsonify, url_for
from .models import Product, Cart, Order
from flask_login import login_required, current_user
from . import db
from intasend import APIService
from .models import Wishlist  # Already imported models



views = Blueprint('views', __name__)

API_PUBLISHABLE_KEY = 'YOUR_PUBLISHABLE_KEY'

API_TOKEN = 'YOUR_API_TOKEN'


@views.route('/')
def home():

    items = Product.query.filter_by(flash_sale=True)

    return render_template('home.html', items=items, cart=Cart.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [])


@views.route('/add-to-cart/<int:item_id>')
@login_required
def add_to_cart(item_id):
    item_to_add = Product.query.get(item_id)
    item_exists = Cart.query.filter_by(product_link=item_id, customer_link=current_user.id).first()
    if item_exists:
        try:
            item_exists.quantity = item_exists.quantity + 1
            db.session.commit()
            flash(f' Quantity of { item_exists.product.product_name } has been updated')
            return redirect(request.referrer)
        except Exception as e:
            print('Quantity not Updated', e)
            flash(f'Quantity of { item_exists.product.product_name } not updated')
            return redirect(request.referrer)

    new_cart_item = Cart()
    new_cart_item.quantity = 1
    new_cart_item.product_link = item_to_add.id
    new_cart_item.customer_link = current_user.id

    try:
        db.session.add(new_cart_item)
        db.session.commit()
        flash(f'{new_cart_item.product.product_name} added to cart')
    except Exception as e:
        print('Item not added to cart', e)
        flash(f'{new_cart_item.product.product_name} has not been added to cart')

    return redirect(request.referrer)


@views.route('/cart')
@login_required
def show_cart():
    cart = Cart.query.filter_by(customer_link=current_user.id).all()
    amount = 0
    for item in cart:
        amount += item.product.current_price * item.quantity

    return render_template('cart.html', cart=cart, amount=amount, total=amount+200)


@views.route('/pluscart')
@login_required
def plus_cart():
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)
        cart_item.quantity = cart_item.quantity + 1
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()

        amount = 0

        for item in cart:
            amount += item.product.current_price * item.quantity

        data = {
            'quantity': cart_item.quantity,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)


@views.route('/minuscart')
@login_required
def minus_cart():
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)
        cart_item.quantity = cart_item.quantity - 1
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()

        amount = 0

        for item in cart:
            amount += item.product.current_price * item.quantity

        data = {
            'quantity': cart_item.quantity,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)


@views.route('removecart')
@login_required
def remove_cart():
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)
        db.session.delete(cart_item)
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()

        amount = 0

        for item in cart:
            amount += item.product.current_price * item.quantity

        data = {
            'quantity': cart_item.quantity,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)


@views.route('/place-order')
@login_required
def place_order():
    customer_cart = Cart.query.filter_by(customer_link=current_user.id).all()  # <-- FIXED .all()

    if customer_cart:
        try:
            total = sum(item.product.current_price * item.quantity for item in customer_cart)

            service = APIService(token=API_TOKEN, publishable_key=API_PUBLISHABLE_KEY, test=True)

            # Replace with actual phone number or store in profile model
            phone = "replace_with_user_phone"

            create_order_response = service.collect.mpesa_stk_push(
                phone_number=phone,
                email=current_user.email,
                amount=total + 200,
                narrative='Purchase of goods'
            )

            for item in customer_cart:
                new_order = Order(
                    quantity=item.quantity,
                    price=item.product.current_price,
                    status=create_order_response['invoice']['state'].capitalize(),
                    payment_id=create_order_response['id'],
                    product_link=item.product_link,
                    customer_link=item.customer_link
                )
                db.session.add(new_order)

                product = Product.query.get(item.product_link)
                product.in_stock -= item.quantity

                db.session.delete(item)

            db.session.commit()
            flash('Order Placed Successfully')
            return redirect('/orders')

        except Exception as e:
            print("Order Error:", e)
            flash('Order not placed')
            return redirect('/')
    else:
        flash('Your cart is empty.')
        return redirect('/')



@views.route('/orders')
@login_required
def order():
    orders = Order.query.filter_by(customer_link=current_user.id).all()
    return render_template('orders.html', orders=orders)


@views.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'POST':
        search_query = request.form.get('search')
        items = Product.query.filter(Product.product_name.ilike(f'%{search_query}%')).all()
        return render_template('search.html', items=items, cart=Cart.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [])

    return render_template('search.html')


@views.route('/wishlist')
@login_required
def wishlist():
    wishlist_items = Wishlist.query.filter_by(customer_link=current_user.id).all()
    return render_template('wishlist.html', wishlist_items=wishlist_items)


@views.route('/add-to-wishlist/<int:product_id>')
@login_required
def add_to_wishlist(product_id):
    existing = Wishlist.query.filter_by(customer_link=current_user.id, product_link=product_id).first()
    if existing:
        flash("Product already in wishlist.")
    else:
        new_item = Wishlist(customer_link=current_user.id, product_link=product_id)
        db.session.add(new_item)
        db.session.commit()
        flash("Product added to wishlist.")
    return redirect(request.referrer or '/')


@views.route('/remove-from-wishlist/<int:item_id>')
@login_required
def remove_from_wishlist(item_id):
    item = Wishlist.query.get(item_id)
    if item and item.customer_link == current_user.id:
        db.session.delete(item)
        db.session.commit()
        flash("Item removed from wishlist.")
    return redirect(url_for('views.wishlist'))

website/templates/add_shop_items.html
{% extends 'base.html' %}

{% block title %} Add Shop Items {% endblock %}


{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Product Name</th>
            <th scope="col">Previous Price</th>
            <th scope="col">Current Price</th>
            <th scope="col">In Stock</th>
            <th scope="col">Picture</th>
            <th scope="col">Flash Sale</th>
            <th scope="col">Add</th>

        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST", enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <td>{{ form.product_name }}</td>
                <td>{{ form.previous_price }}</td>
                <td>{{ form.current_price }}</td>
                <td>{{ form.in_stock }}</td>
                <td>{{ form.product_picture() }}</td>
                <td>{{ form.flash_sale }}</td>
                <td>{{ form.add_product() }}</td>
            </form>
        </tr>
    </tbody>
</table>


{% endblock %}

website/templates/admin.html
{% extends 'base.html' %}

{% block title %} Admin Page {% endblock %}

{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Customers</th>
            <th scope="col">Shop Items</th>
            <th scope="col">Add Shop Items</th>
            <th scope="col">View Orders</th>

        </tr>

    </thead> 
    <tbody>
        <tr>
        <td><a href="/customers">Customers</a></td>
        <td><a href="/shop-items">Shop Items</a></td>
        <td><a href="/add-shop-items">Add Shop Items</a></td>
        <td><a href="/view-orders">View Orders</a></td>
        </tr>
    </tbody>
</table>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" ></script>


    <script src="https://kit.fontawesome.com/e24507d923.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" />

    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>Amazon | {% block title %} {% endblock %}</title>
</head>
<body style="background-color: rgb(124, 14, 151);">


    <!-- navbar section -->
    <nav class="navbar navbar-expand-lg" style="background-color: white;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="color: orange; font-size: 30px; margin-right: -2px;">
          <i class="fa-brands fa-infinity"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/" style="font-family: cursive; font-size: 19px;">Amazon</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-grey" href="#" style="font-size: 17px;">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-grey" href="#" style="font-size: 17px;">Contact us</a>
            </li>
          </ul>

          <form class="d-flex" role="search" action="/search" style="margin-right: 170px;" method="POST">
            <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn" type="submit">Search</button>
          </form>
        </div>

        
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item mx-2" id="items">
            
            {% if cart | length < 1 %}
            <a class="nav-link text-grey" href="/cart"><span class="badge bg-success"></span> Cart
              <i class="fa-solid fa-cart-shopping"></i>
            </a>
            {% else %}
            <a class="nav-link text-grey" href="/cart"><span class="badge bg-success"></span> Cart
              <i class="bi bi-{{ cart | length }}-square-fill"></i>
            </a>
            
            {% endif %}
            
            
          </li>

          <li class="nav-item mx-2" id="items">
            <a class="nav-link text-grey" href="#"><span class="badge bg-success"></span> WishList
              <i class="fa-solid fa-heart"></i>
            </a>
          </li>

          
          <li class="nav-item dropdown mx-2">
            <a class="nav-link dropdown-toggle text-grey" href="#" role="button", id="profileDropdown" 
            data-bs-toggle="dropdown" aria-hidden="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="profileDropdown">

            
              {% if current_user.is_authenticated %}
              <li><a class="dropdown-item" href="/profile/{{ current_user.id }}">Profile <i class="fa-solid fa-user"></i></a></li>
              <li><a class="dropdown-item" href="/orders">Orders <i class="fa-solid fa-truck-fast"></i></a></li>
              <li><a class="dropdown-item" href="/logout">Log Out <i class="fa-solid fa-right-from-bracket"></i></a></li>

              {% else %}
              
              <li><a class="dropdown-item" href="/login">Login <i class="fa-solid fa-right-to-bracket"></i></a></li>

              {% endif %}

            </ul>

          </li>

        </ul>


      </div>
    </nav>


    {% for message in get_flashed_messages() %}

    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    
    </div>
    {% endfor %}

    {% block body %}


    {% endblock %}


    <footer class="container-fluid  text-center p-2 mt-5" style="background-color: orange; color: white;">
      <a href="https://github.com/Frost-Codes" style="color: white;">Amazon</a> | <span>
        <i class="fa-sharp fa-regular fa-copyright"></i></span> 2023 All rights reserved

    </footer>

    <script src="{{ url_for( 'static', filename='js/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/all.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/jquery.js') }}"></script>

    <script src="{{ url_for( 'static', filename='js/myScript.js') }}"></script>



</body>
    






    
    
</body>
</html>

website/templates/change_password.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="col-sm-5 offset-sm-3" style="background-color: white; border-radius: 10px; margin-top: 20px;">

    <form style="padding: 30px;" method="POST">
    
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.current_password.label }}</label>
            {{ form.current_password }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.new_password.label }}</label>
            {{ form.new_password }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.confirm_new_password.label }}</label>
            {{ form.confirm_new_password }}
        </div>

        {{ form.change_password }}
    
    </form>

</div>

{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="container text-center">
    <div class="row" style="margin: 10px;">
      <div class="col " style="margin: 3px;">
        <div class="list-group" id="right1">
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                <span class="link-name">Supermarket</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span class="link-name">Health & Beuty</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa-solid fa-comment"></i>                
                <span class="link-name">Home & Office</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-camera" aria-hidden="true"></i>
                <span class="link-name">Fashion</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-audio-description" aria-hidden="true"></i>
                <span class="link-name">Electronics</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-cubes" aria-hidden="true"></i>
                <span class="link-name">Gaming</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-child" aria-hidden="true"></i>
                <span class="link-name">Baby Products</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-bicycle" aria-hidden="true"></i>
                <span class="link-name">Sporting Goods</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-binoculars" aria-hidden="true"></i>
                <span class="link-name">Garden & Outdoor</span>
            </a>

        </div>
      </div>


      <div class="col-md-7" style="margin: 3px;">
        <img src="../static/images/center.gif" alt="" style="width: 600px; height: 365px; border-radius: 10px;">
      </div>
      <div class="col-md-2">
        <div class="row" style="background-color: white; border-radius: 10px;">
        
            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/help.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">HELP CENTER</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">Customer care</p>
                </div>
            </div>

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/return.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">EASY RETURN</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">Quick Refund</p>
                </div>
            </div>

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/payment.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">SELL ON AMAZON</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">FBA Program</p>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 12px;">
            <div class="col">
                <img src="../static/images/right2.gif" alt="" class="right2">
            </div>
        
        </div>
      </div>
    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px;">
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/techweek.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Tech Week</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/FreeDelivery.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Free Delivery</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/food.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Amazon Food</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/airtime.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Airtime & Bills</h6>
        </div>
 
    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px; background-color: rgb(219, 218, 218);" id="column">

        {% for item in items %}

        <div class="col" style="background-color: white;">
        
            <img src="{{ item.product_picture }}" alt="" style="height: 202px; width: 180px; border-radius: 10px;">

            <div class="row" style="margin-top: 5px;">
                <h6 style="color: gray;">{{ item.product_name }}</h6>
            </div>

            <div class="row" style="margin-top: 10px;">
            
                <div class="col">

                    <h5 style="font-weight: 600; font-family: 'Times New Roman', Times, serif;">Ksh {{ item.current_price }}</h5>
                    <strike><p style="color: gray;">Ksh {{ item.previous_price}}</p></strike>
                </div>

                <div class="col">
                    <a href="/add-to-cart/{{ item.id }}">Add</a>
                </div>
            
            </div>

            <div class="row">
                <p>{{ item.in_stock }} Items Left</p>
            </div>
        </div>
    
        {% endfor %}

    </div>
</div>


{% endblock %}

website/templates/login.html
{% extends 'forms.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<!-- Login section start -->

<section class="base" id="base-signup">
    <div class="base-content">
        <div class="form">
            <h3>
                Login to start <br> Shopping
            </h3>
            
            <hr class="first">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="email"><h4>Email Address</h4>{{ form.email }} <hr></div>
                <div class="password"><h4>Password</h4>{{ form.password }} <hr></div>

                <div class="buttons">
                    <a href="/sign-up"> Sign Up</a>
                    {{ form.submit() }}
                </div>


            </form>
        </div>
    </div>
</section>


{% endblock %}

website/templates/order_update.html
{% extends 'base.html' %}

{% block title %} Update Order {% endblock %}


{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Order Status</th>
            <th scope="col">Order Status</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <td>{{ form.order_status }}</td>
                <td>{{ form.update() }}</td>
            </form>
        </tr>
    </tbody>
</table>

{% endblock %}

website/templates/orders.html
{% extends 'base.html' %}

{% block title %} Orders {% endblock %}

{% block body %}

<div class="container my-5">

    <div class="row">
        {% if orders %}

        <h1 class="text-center mb-5" style="color: white;">Orders</h1>
        <div class="col-sm-13">
            <div class="card">
                <div class="card-body">
                    <!-- <h3>Orders</h3> -->
                    {% for item in orders %}

                    <div class="row">
                        <div class="col-sm-3 text-center align-self-center">
                            <img src="{{ item.product.product_picture }}" alt="" class="img-fluid img-thumbnail shadow-sm" height="150px" width="150px">
                        </div>
                        <div class="col-sm-7">
                            
                            <h3>{{ item.product.product_name }}</h3>
                            <p class="mb-2 text-muted small">Quantity: {{ item.quantity }}</p>
                            <p class="mb-2 text-muted small">Price: Ksh {{ item.price }}</p>
                               
                                
                            <div class="col-sm-4">
                                <p>Order Status: {{ item.status }}</p>
                                {% if item.status == 'Pending' %}
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 20%;"  aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Accepted' %}
                                <div class="progress">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 40%;"  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Out for delivery' %}
                                <div class="progress">
                                    <div class="progress-bar bg-warning" role="progressbar" style="width: 70%;"  aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Delivered' %}
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%;"  aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Canceled' %}
                                <div class="progress">
                                    <div class="progress-bar bg-danger" role="progressbar" style="width: 100%;"  aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                {% endif %}
                            </div>
                            
                        </div>
                    </div>
                    <hr class="text-muted">
                    {% endfor %}
                </div>
            </div>
        </div>

        {% else %}
        <h1 class="text-center mb-5" style="color: white;">You have no Orders</h1>

        {% endif %}
    </div>

</div>

{% endblock %}

website/templates/profile.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="container my-5">
    <div class="row">
        <h3 style="color: white;">Welcome <span class="text-capitalize">{{ customer.username }}</span></h3>

        <div class="col-sm-2 border-end" style="margin-top: 20px;">
        
            <ul class="list-unstyled">
                <li class="d-grid"><a href="#" class="btn btn-primary">Profile</a></li>
                <li class="d-grid"><a href="/change-password/{{ customer.id }}" class="btn btn-primary" style="margin-top: 5px;">Change Password</a></li>

            </ul>
        
        </div>

        <div class="col-sm-5 offset-sm-1" style="background-color: white; border-radius: 18px; margin-top: 20px;">
            <div class="row">

                <div class="col-sm-8">
                    <div class="card m-2">

                        <h3>{{ customer.username }}</h3>
                        <p>Email: {{ customer.email }}</p>
                    </div>
                </div>

            </div>
        
        </div>
    </div>
</div>

{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block title %} Search {% endblock %}


{% block body %}

{% if items | length < 1 %}
<h3 style="color: white;">No Items Match your Search query</h3>

{% else %}


<div class="container text-center">
    <div class="row" style="margin: 8px; background-color: rgb(219, 218, 218);" id="column">

        {% for item in items %}

        <div class="col" style="background-color: white;">
        
            <img src="{{ item.product_picture }}" alt="" style="height: 202px; width: 180px; border-radius: 10px;">

            <div class="row" style="margin-top: 5px;">
                <h6 style="color: gray;">{{ item.product_name }}</h6>
            </div>

            <div class="row" style="margin-top: 10px;">
            
                <div class="col">

                    <h5 style="font-weight: 600; font-family: 'Times New Roman', Times, serif;">Ksh {{ item.current_price }}</h5>
                    <strike><p style="color: gray;">Ksh {{ item.previous_price}}</p></strike>
                </div>

                <div class="col">
                    <a href="/add-to-cart/{{ item.id }}">Add</a>
                </div>
            
            </div>

            <div class="row">
                <p>{{ item.in_stock }} Items Left</p>
            </div>
        </div>
    
        {% endfor %}

    </div>
</div>

{% endif %}

{% endblock %}

website/templates/signup.html
{% extends 'forms.html' %}

{% block title %} Sign Up {% endblock %}

{% block body %}

<!-- Sign Up section start -->

<section class="base" id="base-signup">
    <div class="base-content">
        <div class="form">
            <h3>
                Create an account <br> to shop
            </h3>
            
            <hr class="first">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="email"><h4>Email Address</h4>{{ form.email }} <hr> </div>
                <div class="name"><h4>User Name</h4>{{ form.username }} <hr></div>
                <div class="password"><h4>Password</h4>{{ form.password1 }} <hr></div>
                <div class="password"><h4>Confirm Passowrd</h4>{{ form.password2 }} <hr></div>

                <div class="buttons">
                    <a href="/login"> Login</a>
                    {{ form.submit() }}
                </div>


            </form>
        </div>
    </div>
</section>


{% endblock %}

website/templates/wishlist.html
<h2>Your Wishlist</h2>
{% if wishlist_items %}
    <ul>
        {% for item in wishlist_items %}
            <li>
                {{ item.product.product_name }} - ₹{{ item.product.current_price }}
                <a href="{{ url_for('views.remove_from_wishlist', item_id=item.id) }}">Remove</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No items in wishlist.</p>
{% endif %}